### ISSUE TITLE
Rails .state file

### ISSUE THREAD

**Issue by mauu-alpha** [ylecuyer/puma-status#13]
Im a little confused, where i can find the `.state` file generated by rails (or sidekiq) to monitor it?

**Comment by ylecuyer** [comment]
This `.state` file is managed by puma the webserver, not rails nor sidekiq.

In the puma config, you can change the path with `state_path` https://github.com/puma/puma/blob/master/lib/puma/dsl.rb#L459, you'll also have to enable the control server: https://github.com/puma/puma#controlstatus-server
