### ISSUE TITLE
Make compatible with Ruby 2.2

### ISSUE THREAD

**Issue by arianf** [ylecuyer/puma-status#18]
I get the following when I install it:
`Gem::RuntimeRequirementNotMetError: puma-status requires Ruby version >= 2.3.0`

(I know Ruby 2.2 is EOL)

**Comment by ylecuyer** [comment]
Hello @arianf, I'm curious and would like to now the reasons preventing you from running puma-status with a recent version of ruby?

puma-status is independent and doesn't have to be in your Gemfile to run (this is a wild guess), you can install it with `gem install puma-status`. This way you don't have to make your code ruby >2.3 compatible to use it.

if puma-status isn't in your Gemfile and it is your system ruby version which is blocking you then you can use something like rbenv : `RBENV_VERSION=2.3.0 puma-status`

**Comment by arianf** [comment]
I am running this Rails app within docker, `FROM ruby:2.2.10` which doesn't have RBENV or RVM

**Comment by seuros** [comment]
@arianf you can just bump your ruby version in the docker file. that ruby of version is EOL for years.

**Comment by ylecuyer** [comment]
Following https://github.com/ylecuyer/puma-status/pull/26 and the parallel ruby constraint I'm closing this issue as puma-status will now require at least ruby 2.5

For the record, to run, puma-status only needs access to the state file and the control server of puma which can be either a unix socket or a tcp socket (depends on puma configuration). In either case, those can be made available outside of the running docker image and processed by another docker image with puma-status and the proper ruby version running
